"""auto update

Revision ID: 1202759a99cf
Revises: 6faabb69ff83
Create Date: 2026-02-08 01:11:49.270673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1202759a99cf'
down_revision: Union[str, Sequence[str], None] = '6faabb69ff83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('custom_api_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('custom_api_base_url', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('custom_api_key', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('custom_api_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'custom_api_model')
    op.drop_column('user_settings', 'custom_api_key')
    op.drop_column('user_settings', 'custom_api_base_url')
    op.drop_column('user_settings', 'custom_api_enabled')
    # ### end Alembic commands ###